[project]
name = "hw2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.0.0",
    "ipykernel>=7.1.0",
    "nbconvert>=7.16.6",
    "pandas>=2.3.3",
    "pandas-stubs~=2.3.3",
    "vega-datasets>=0.9.0",
]
